### PR TITLE
Support modal input via ctrl-:

### PR DESCRIPTION
**Pull request by andir**
This enables users to input more fancy stuff (like emojis) through a native
Gtk Entry element (where you can just hit ctrl-. for emoji selection).

### CODE REVIEW

**Comment by flokli** [comment]
Is there a way to make that modal window a bit bigger, or have the emoji picker open in its own pane?

The input box modal windowIt opens as floating here (in the size of the single text box):

image

If I now press `Ctrl-.`, the emoji picker is pretty much unusable, as it's inside that modal window itself (and cropped off):

image

**Comment by andir** [comment]
On 17:31 22.12.20, Florian Klink wrote:
> Is there a way to make that modal window a bit bigger, or have the emoji picker open in its own pane?
We can probably start using pixels and stuff here.. I really do not want
to start harcoding things tho..


> The input box modal windowIt opens as floating here (in the size of the single text box):
> image
> If I now press `Ctrl-.`, the emoji picker is pretty much unusable, as it's inside that modal window itself (and cropped off):
> image

I see. I only ever use it via the text input and do not click on the
buttons thus I never noticed that... For me the floating window is
visible and works just fine on sway (except for clicking on things
outside of the window doesn't work). On X11 I can reproduce the size
problem.

Any ideas how we can make the dialog's size dyanmic based on the emoji
picker it opens without hardcoding sizes?

**Comment by andir** [comment]
On 17:31 22.12.20, Florian Klink wrote:
> Is there a way to make that modal window a bit bigger, or have the emoji picker open in its own pane?
> 
> The input box modal windowIt opens as floating here (in the size of the single text box):
> 
> image
> 
> If I now press `Ctrl-.`, the emoji picker is pretty much unusable, as it's inside that modal window itself (and cropped off):
> 
> image
> 

This seems to be the upstream discussion of this issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/3307

**Comment by flokli** [comment]
Thanks for the pointers!

**Comment by andir** [comment]
@flokli: Seems to be fixed in 4.1.0: https://gitlab.gnome.org/GNOME/gtk/-/blob/4.1.0/NEWS#L10-11 so the gtk4 upgrade should also fix that bug

**Pull request merged**
